spring:
  application:
    name: rest-service1-6

  rabbitmq:
    host: rabbitmq

  zipkin:
    baseUrl: http://rest-service1-collector:9412/
  sleuth:
    sampler:
      percentage: 1.0
      
  cloud:
    stream:
      bindings:
        input:
          destination: my-rest-service1-queue-1
          contentType: text/plain
          binder: rabbit

server:
  port: 16006