server:
  port: 18888

spring:
  application:
    name: ts-assurance-service1
  data:
    mongodb:
#      host: ts-assurance-mongo
      host: localhost
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

swagger:
  controllerPackage: assurance.controller