spring:
  application:
    name: ts-station-service
  data:
    mongodb:
#      host: ts-station-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017
      host: 127.0.0.1

# HTTP Server
server:
  port: 12345  # HTTP (Tomcat) port

swagger:
  controllerPackage: fdse.microservice