apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rest-service1-1-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: rest-service1-1
    spec:
      containers:
      - name: rest-service1-1
        image: 10.141.212.25:5555/rest-service1-1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 16001

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rest-service1-2-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: rest-service1-2
    spec:
      containers:
      - name: rest-service1-2
        image: 10.141.212.25:5555/rest-service1-2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 16002