apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: rest-service1-delay
spec:
  destination:
    name: rest-service1-2
  route:
  - labels:
      version: v1
  httpFault:
    delay:
      percent: 100
      fixedDelay: 4s






