apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rest-service1-1-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: rest-service1-1
    spec:
      containers:
      - name: rest-service1-1
        image: 10.141.212.25:5555/rest-service1-1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 16001
      - name: istio-proxy
        image: docker.io/istio/proxy_debug:0.2.6
      initContainers:
      - name: istio-init
        image: docker.io/istio/proxy_init:0.2.6
        imagePullPolicy: IfNotPresent