apiVersion: v1
kind: Service
metadata:
  name: rest-service1-1
spec:
  type: NodePort
  ports:
    - name: http-service1
      port: 16001
      nodePort: 30001
  selector:
   app: rest-service1-1

---

apiVersion: v1
kind: Service
metadata:
    name: rest-service1-2
spec:
    type: NodePort
    ports:
       - name: http-service2
         port: 16002
         nodePort: 30002
    selector:
        app: rest-service1-2