# HTTP Server
server:
  port: 19001  # HTTP (Tomcat) port

spring:
  application:
    name: ts-payment-service
  data:
    mongodb:
#      host: ts-payment-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017
      host: 127.0.0.1

swagger:
  controllerPackage: com.trainticket.controller