server:
  port: 12347

spring:
  application:
    name: ts-contacts-service1
  data:
    mongodb:
      host: 127.0.0.1
#      host: ts-contacts-mongo
      database: ts
      port: 27017

swagger:
  controllerPackage: contacts.controller