spring:
  application:
    name: rest-service1-end
    
  rabbitmq:
    host: rabbitmq

  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
      
  cloud:
    stream:
      bindings:
        output:
          destination: my-rest-service1-queue-1
          contentType: text/plain
          binder: rabbit

server:
  port: 16000